### ISSUE TITLE
cannot import name Module

### ISSUE THREAD

**Issue by nightsnake** [algernon/mojology#2]
Hi!
I have debian jessie and python 2.7
i tried to install according to README, but failed.

`(mojology)root@telelog:/opt/mojology# python server.py
Traceback (most recent call last):
  File "server.py", line 18, in <module>
    from mojology import Mojology
  File "/opt/mojology/mojology/__init__.py", line 21, in <module>
    from mojology.views.browser import browser
  File "/opt/mojology/mojology/views/browser.py", line 22, in <module>
    from flask import Module, g, url_for, render_template, Markup, abort
ImportError: cannot import name Module
`

Can you help me?

**Comment by algernon** [comment]
I suppose flask changed quite a bit since the last time I touched this project. Perhaps installing an older flask would work?

```
$ pip uninstall flask
$ pip install flask==0.6
```

**Comment by nightsnake** [comment]
`Exception:
Traceback (most recent call last):
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/download.py", line 546, in unpack_http_url
    resp = session.get(target_url, stream=True)
  File "/opt/mojology/lib/python-wheels/requests-2.4.3-py2.py3-none-any.whl/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/opt/mojology/local/lib/python2.7/site-packages/pip/download.py", line 237, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/mojology/lib/python-wheels/requests-2.4.3-py2.py3-none-any.whl/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/mojology/lib/python-wheels/requests-2.4.3-py2.py3-none-any.whl/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/opt/mojology/lib/python-wheels/requests-2.4.3-py2.py3-none-any.whl/requests/adapters.py", line 422, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='pypi.python.org', port=443): Read timed out. (read timeout=15)

Storing debug log for failure in /root/.pip/pip.log
`

**Comment by algernon** [comment]
That sounds like an issue with pypi, the request timed out while trying to download from there. Can you try again, after veryfing that pypi.python.org loads in the browser?

**Comment by nightsnake** [comment]
Thank you. it helps!
